import json, re

text = open('questions_upsc.js', encoding='utf-8').read()
data = json.loads(re.sub(r'^const questions_upsc = ', '', text).rstrip(';\n'))

print("Current counts:", {k: len(v) for k, v in data.items()})

# ---- 450 Polity questions ----
polity_qs = [
    {"question": "The Constitution of India was adopted on?", "answer": "26 November 1949"},
    {"question": "How many Fundamental Rights are guaranteed by the Indian Constitution?", "answer": "6"},
    {"question": "Who is the guardian of the Indian Constitution?", "answer": "Supreme Court"},
    {"question": "The Right to Education was added to the Constitution by which amendment?", "answer": "86th Amendment"},
    {"question": "Which article of the Constitution abolishes untouchability?", "answer": "Article 17"},
    {"question": "The concept of 'Directive Principles of State Policy' was borrowed from?", "answer": "Irish Constitution"},
    {"question": "The President of India is elected by?", "answer": "An Electoral College"},
    {"question": "Which article provides for the creation of an All India Services?", "answer": "Article 312"},
    {"question": "The Preamble of the Indian Constitution was amended by which amendment?", "answer": "42nd Amendment"},
    {"question": "The first Lok Sabha was constituted in?", "answer": "1952"},
    {"question": "Which schedule of the Indian Constitution lists the recognized languages?", "answer": "Eighth Schedule"},
    {"question": "Who holds the power to dissolve the Lok Sabha?", "answer": "President on advice of Prime Minister"},
    {"question": "The concept of 'Fundamental Duties' was added by which amendment?", "answer": "42nd Amendment"},
    {"question": "Who appoints the Chief Election Commissioner of India?", "answer": "President of India"},
    {"question": "How many seats are there in the Rajya Sabha?", "answer": "250"},
    {"question": "Which article deals with the Right to Equality?", "answer": "Articles 14 to 18"},
    {"question": "The emergency provisions in the Indian Constitution were borrowed from?", "answer": "German Constitution (Weimar)"},
    {"question": "Who was the Chairman of the Constituent Assembly of India?", "answer": "Dr. Rajendra Prasad"},
    {"question": "The Indian Parliament consists of?", "answer": "Lok Sabha, Rajya Sabha, and the President"},
    {"question": "Which article allows the President to declare a Financial Emergency?", "answer": "Article 360"},
    {"question": "The maximum strength of the Lok Sabha is?", "answer": "552"},
    {"question": "Judicial Review in India is related to which article?", "answer": "Article 13"},
    {"question": "Which commission is associated with local self-government in India?", "answer": "State Finance Commission"},
    {"question": "The term 'Secular' was added to the Preamble by which amendment?", "answer": "42nd Amendment, 1976"},
    {"question": "The concept of written constitution was borrowed from?", "answer": "USA"},
    {"question": "Which article provides for freedom of religion?", "answer": "Article 25 to 28"},
    {"question": "Who was the first Chief Election Commissioner of India?", "answer": "Sukumar Sen"},
    {"question": "The Rajya Sabha is a permanent body and cannot be dissolved. True or False?", "answer": "True"},
    {"question": "Which article deals with Right against Exploitation?", "answer": "Articles 23 and 24"},
    {"question": "The 73rd Constitutional Amendment deals with?", "answer": "Panchayati Raj institutions"},
    {"question": "Article 19 of the Indian Constitution guarantees?", "answer": "Six freedoms to citizens"},
    {"question": "Who has the power to summon the Houses of Parliament?", "answer": "President of India"},
    {"question": "The idea of a 'Constitution' was first introduced by which country?", "answer": "USA"},
    {"question": "Which court has jurisdiction over disputes between states?", "answer": "Supreme Court of India"},
    {"question": "The Speaker of Lok Sabha is elected by?", "answer": "Members of Lok Sabha"},
    {"question": "What is the minimum age to become the President of India?", "answer": "35 years"},
    {"question": "Which article deals with National Emergency?", "answer": "Article 352"},
    {"question": "The term of the President of India is?", "answer": "5 years"},
    {"question": "Constitutional morality was emphasized by which leader in the Constituent Assembly?", "answer": "B. R. Ambedkar"},
    {"question": "The concept of 'Residuary Powers' in India is with whom?", "answer": "Union/Centre"},
    {"question": "Under which article can the President impose President's Rule?", "answer": "Article 356"},
    {"question": "Which amendment brought Panchayati Raj into the Constitution?", "answer": "73rd Amendment"},
    {"question": "The Anti-defection law is included in which schedule?", "answer": "Tenth Schedule"},
    {"question": "Who appoints the Attorney General of India?", "answer": "President of India"},
    {"question": "The Right to Privacy was declared a fundamental right by the Supreme Court in?", "answer": "2017"},
    {"question": "Which article deals with the Equal Protection of law?", "answer": "Article 14"},
    {"question": "The idea of Judicial Review was borrowed from?", "answer": "USA"},
    {"question": "Who has the authority to remove the Vice President?", "answer": "Rajya Sabha (with Lok Sabha concurrence)"},
    {"question": "The Chief Justice of India is appointed by?", "answer": "President on the recommendation of collegium"},
    {"question": "The first session of the Constituent Assembly was held in?", "answer": "December 1946"},
    {"question": "Which list deals with concurrent powers of Centre and States?", "answer": "Concurrent List"},
    {"question": "Who has the power to grant pardons under Article 72?", "answer": "President of India"},
    {"question": "The Comptroller and Auditor General of India is appointed by?", "answer": "President of India"},
    {"question": "What is the meaning of 'Writ of Habeas Corpus'?", "answer": "Produce the body (protects against illegal detention)"},
    {"question": "The concept of 'Federalism' was borrowed from the Constitution of?", "answer": "Canada"},
    {"question": "How many union territories does India currently have?", "answer": "8"},
    {"question": "The first General Elections in India were held in?", "answer": "1951-52"},
    {"question": "Who can impeach the President of India?", "answer": "Both Houses of Parliament"},
    {"question": "Which article gives right to citizens to move the Supreme Court for enforcement of Fundamental Rights?", "answer": "Article 32"},
    {"question": "Which amendment reduced the voting age from 21 to 18 years?", "answer": "61st Amendment"},
    {"question": "The Collegium System is related to?", "answer": "Appointment of judges in higher courts"},
    {"question": "Under the Indian Constitution, who is the Commander-in-Chief?", "answer": "President of India"},
    {"question": "Which article provides for freedom of the press?", "answer": "Article 19(1)(a)"},
    {"question": "The Universal Adult Franchise means?", "answer": "Every adult citizen has the right to vote"},
    {"question": "Which body in India recommends delimitation of constituencies?", "answer": "Delimitation Commission"},
    {"question": "The DPSP in Part IV of the Constitution are?", "answer": "Non-justiciable"},
    {"question": "Which article of the Constitution speaks about the right to life and personal liberty?", "answer": "Article 21"},
    {"question": "The term of members of Rajya Sabha is?", "answer": "6 years"},
    {"question": "Bicameralism was borrowed from which country?", "answer": "United Kingdom"},
    {"question": "The Consolidated Fund of India is under which article?", "answer": "Article 266"},
    {"question": "Who was the first Prime Minister of India?", "answer": "Jawaharlal Nehru"},
    {"question": "The Finance Commission is constituted by?", "answer": "President of India"},
    {"question": "Which article deals with the election of Vice President?", "answer": "Article 66"},
    {"question": "The idea of a Preamble in the Constitution was borrowed from?", "answer": "USA"},
    {"question": "Who can issue writs for enforcement of Fundamental Rights?", "answer": "Supreme Court and High Courts"},
    {"question": "Which is the largest High Court in India?", "answer": "Allahabad High Court"},
    {"question": "The National Human Rights Commission was established in?", "answer": "1993"},
    {"question": "The system of 'Single Citizenship' in India was borrowed from?", "answer": "United Kingdom"},
    {"question": "Under which article can Parliament declare an area as a Disturbed Area?", "answer": "Article 355"},
    {"question": "Which writ is issued to prevent a person from acting in an unauthorized manner?", "answer": "Writ of Prohibition"},
    {"question": "The concept of 'Basic Structure Doctrine' was established in?", "answer": "Kesavananda Bharati case (1973)"},
    {"question": "Which article defines Indian Citizenship?", "answer": "Articles 5 to 11"},
    {"question": "The Right to Information Act was passed in?", "answer": "2005"},
    {"question": "What is the maximum gap allowed between two sessions of Parliament?", "answer": "6 months"},
    {"question": "The advisory jurisdiction of the Supreme Court enables the President to?", "answer": "Seek the opinion of the Supreme Court on legal questions"},
    {"question": "Which Fundamental Right cannot be suspended even during an Emergency?", "answer": "Articles 20 and 21"},
    {"question": "The State Legislature in a state with a bicameral legislature includes?", "answer": "Governor, Legislative Assembly (Vidhan Sabha), and Legislative Council (Vidhan Parishad)"},
    {"question": "Which article deals with the Comptroller and Auditor-General of India?", "answer": "Article 148"},
    {"question": "The Preamble declares India to be a?", "answer": "Sovereign, Socialist, Secular, Democratic Republic"},
    {"question": "Which article of the Constitution provides for the creation of the Rajya Sabha?", "answer": "Article 80"},
    {"question": "Who has the power to increase the number of judges in the Supreme Court?", "answer": "Parliament"},
    {"question": "Which article deals with equal pay for equal work?", "answer": "Article 39(d) (DPSP)"},
    {"question": "The concept of 'Natural Justice' in Indian law includes?", "answer": "Audi alteram partem and Nemo judex in causa sua"},
    {"question": "The National Commission for Women was established in?", "answer": "1992"},
    {"question": "Which amendment inserted the Right to Education as a Fundamental Right?", "answer": "86th Amendment"},
    {"question": "The Chief Minister of a state is appointed by?", "answer": "Governor"},
    {"question": "Which body can create a new All India Service?", "answer": "Rajya Sabha (by 2/3rd majority)"},
    {"question": "The Gram Panchayat is the basic unit of?", "answer": "Panchayati Raj"},
    {"question": "The provision for an 'Integrated Audit' in India is maintained by?", "answer": "CAG"},
    {"question": "Which writ means 'we command'?", "answer": "Mandamus"},
    {"question": "The impeachment of the President of India is outlined in?", "answer": "Article 61"},
    {"question": "Which part of the Indian Constitution deals with Citizenship?", "answer": "Part II"},
    {"question": "What is the minimum number of members required for a Gram Sabha?", "answer": "Voters in a village who are registered in electoral rolls"},
    {"question": "The National Development Council was set up in?", "answer": "1952"},
    {"question": "Right to Constitutional Remedies is described in?", "answer": "Article 32"},
    {"question": "Who presides over joint sittings of both Houses of Parliament?", "answer": "Speaker of Lok Sabha"},
    {"question": "Which body is described as the 'Fourth Estate'?", "answer": "The Press / Media"},
    {"question": "The concept of 'Rule of Law' was largely borrowed from?", "answer": "United Kingdom"},
    {"question": "Which article of the Indian Constitution provides for equality before law?", "answer": "Article 14"},
    {"question": "Who is the ex-officio Chairman of the Rajya Sabha?", "answer": "Vice President of India"},
    {"question": "Which amendment of the Constitution added Sikkim as a state?", "answer": "36th Amendment"},
    {"question": "How many members are nominated to Lok Sabha by the President?", "answer": "2 (from Anglo-Indian community) - abolished by 104th Amendment"},
    {"question": "What is the minimum age to vote in Indian elections?", "answer": "18 years"},
    {"question": "The concept of 'Equality of Opportunity' is enshrined in?", "answer": "Article 16"},
    {"question": "The original Constitution of India had how many schedules?", "answer": "8"},
    {"question": "The National Emergency declared in 1975 is also called?", "answer": "The Internal Emergency"},
    {"question": "Under article 368, amendments to the Constitution can be made by?", "answer": "Special majority of Parliament"},
    {"question": "The Indian Constitution has drawn its concept of 'Liberty, Equality, Fraternity' from?", "answer": "The French Revolution"},
    {"question": "Which article defines the composition of the Parliament?", "answer": "Article 79"},
    {"question": "The first woman Chief Justice of a High Court in India was?", "answer": "Leila Seth"},
    {"question": "The District Collector is appointed by?", "answer": "State Government"},
    {"question": "Mandal Commission was related to?", "answer": "Other Backward Classes (OBCs) reservations"},
    {"question": "Which article of the Constitution makes the Supreme Court the court of record?", "answer": "Article 129"},
    {"question": "Local self-government in urban areas is covered under?", "answer": "74th Constitutional Amendment"},
    {"question": "The concept of 'Cabinet Responsibility' was borrowed from?", "answer": "United Kingdom"},
    {"question": "Article 343 of the Constitution declares which language as official language?", "answer": "Hindi"},
    {"question": "What is the 'Money Bill' in the Indian Parliament?", "answer": "A bill related only to taxation or expenditure"},
    {"question": "Which article provides for the appointment of the Prime Minister?", "answer": "Article 75"},
    {"question": "The Governor of a State is appointed by?", "answer": "President of India"},
    {"question": "Which article provides for the Union Public Service Commission?", "answer": "Article 315"},
    {"question": "The 'Doctrine of Eclipse' in Indian Constitutional law refers to?", "answer": "Pre-Constitutional laws inconsistent with Fundamental Rights become dormant"},
    {"question": "The Indian Constitution uses the term 'Federation' in which article?", "answer": "It does not; India is described as a Union of States"},
    {"question": "The original members of the Constituent Assembly represented?", "answer": "Provinces of British India and Princely States"},
    {"question": "Which article deals with protection against arbitrary arrest?", "answer": "Article 22"},
    {"question": "The President of India cannot dissolve which House?", "answer": "Rajya Sabha"},
    {"question": "By which amendment was the voting age reduced from 21 to 18?", "answer": "61st Amendment (1988)"},
    {"question": "Which article provides for the Supreme Court's original jurisdiction?", "answer": "Article 131"},
    {"question": "Inter-state water disputes are settled by?", "answer": "Tribunal constituted by Parliament"},
    {"question": "The power to summon and prorogue Parliament rests with?", "answer": "President"},
    {"question": "The concept of 'Co-operative Federalism' means?", "answer": "Centre and States working together"},
    {"question": "Who conducts elections to Panchayati Raj institutions?", "answer": "State Election Commission"},
    {"question": "Which article deals with the right against self-incrimination?", "answer": "Article 20(3)"},
    {"question": "The 'Question Hour' in Parliament is for?", "answer": "Members to ask questions to Ministers"},
    {"question": "The Concurrent List was borrowed from which country's constitution?", "answer": "Australia"},
    {"question": "Which case established the 'Basic Structure Doctrine'?", "answer": "Kesavananda Bharati v. State of Kerala (1973)"},
    {"question": "The 'Zero Hour' in Parliament refers to?", "answer": "The time for raising urgent matters without prior notice"},
    {"question": "The Election Commission of India is a?", "answer": "Constitutional body"},
    {"question": "Which article deals with the election of Members of Parliament?", "answer": "Article 81 (Lok Sabha)"},
    {"question": "Which body is also known as the 'Upper House' of the Indian Parliament?", "answer": "Rajya Sabha"},
    {"question": "The Foreign Ministers of India are called?", "answer": "External Affairs Minister"},
    {"question": "The concept of 'Certiorari' refers to?", "answer": "A writ quashing the proceedings of a lower court"},
    {"question": "Which year saw the Balwantray Mehta Committee recommendations on Panchayati Raj?", "answer": "1957"},
    {"question": "The Public Account Committee in Parliament examines?", "answer": "Appropriation Accounts and Audit Reports"},
    {"question": "The Contingency Fund of India is under?", "answer": "President's disposal"},
    {"question": "In which schedule are the DPSPs mentioned?", "answer": "Part IV (Articles 36-51), not a Schedule"},
    {"question": "The Union List contains how many subjects (original)?", "answer": "97 subjects"},
    {"question": "Which article gives the Parliament power to form new states?", "answer": "Article 3"},
    {"question": "The National Commission for Backward Classes was established by?", "answer": "National Commission for Backward Classes Act, 1993"},
    {"question": "Right to Vote in India is a?", "answer": "Legal right (Constitutional provision under Article 326)"},
    {"question": "The ordinance-making power of the President is under?", "answer": "Article 123"},
    {"question": "Which article allows reservation for women in Panchayats?", "answer": "Article 243D"},
    {"question": "What is 'Prorogation' of Parliament?", "answer": "Ending a session of Parliament without dissolving it"},
    {"question": "The 'No Confidence Motion' can be moved only against?", "answer": "Council of Ministers (Government)"},
    {"question": "The authority to amend the Constitution lies with?", "answer": "Parliament of India"},
    {"question": "Who nominates 12 members to the Rajya Sabha?", "answer": "President of India"},
    {"question": "The concept of Separation of Powers was borrowed from?", "answer": "USA"},
    {"question": "Which article of the Indian Constitution deals with the election of the President?", "answer": "Article 54"},
    {"question": "Under which article can a law be declared unconstitutional?", "answer": "Article 13"},
    {"question": "The Council of States is an alternative name for?", "answer": "Rajya Sabha"},
    {"question": "The Chief Justice of India administers oath to?", "answer": "The President of India"},
    {"question": "Who administers the oath to the Chief Justice of India?", "answer": "President of India"},
    {"question": "In case of a tie in the Rajya Sabha, who casts the deciding vote?", "answer": "Chairman (Vice President)"},
    {"question": "The Comptroller and Auditor General of India reports to?", "answer": "Parliament"},
    {"question": "Which article deals with the rights of minorities to establish educational institutions?", "answer": "Article 30"},
    {"question": "Who can remove the Chief Justice of India?", "answer": "President (after impeachment by Parliament)"},
    {"question": "The National Minorities Commission is a statutory body established by?", "answer": "National Commission for Minorities Act, 1992"},
    {"question": "Which amendment gave Constitutional status to Panchayati Raj institutions?", "answer": "73rd Amendment"},
    {"question": "Under Article 352, the term 'Armed Rebellion' was inserted by which amendment?", "answer": "44th Amendment"},
    {"question": "The Supreme Court has how many seats at present?", "answer": "34 (CJI + 33 judges)"},
    {"question": "Which article deals with the Attorney General of India?", "answer": "Article 76"},
    {"question": "What does 'Quo Warranto' mean?", "answer": "By what authority (challenges unlawful holding of a public office)"},
    {"question": "The Indian Constitution is neither purely federal nor purely unitary; it is?", "answer": "Quasi-federal"},
    {"question": "Which ministry handles elections in India?", "answer": "No ministry; Election Commission is autonomous"},
    {"question": "The 'Special Leave Petition' in India goes to?", "answer": "Supreme Court under Article 136"},
    {"question": "Who appoints the members of State Public Service Commission?", "answer": "Governor"},
    {"question": "Which article provides for the formation of the Planning Commission?", "answer": "No specific article; it was an executive body"},
    {"question": "The office of the 'Ombudsman' or 'Lokpal' was established in India in year?", "answer": "2014"},
    {"question": "Which is Article 19(1)(a) related to?", "answer": "Freedom of speech and expression"},
    {"question": "The concept of 'Sunset Clause' in legislation means?", "answer": "A law that automatically expires after a specified date"},
    {"question": "The Governor can withhold assent to which type of bills?", "answer": "State Bills"},
    {"question": "Which article deals with the formation of new states and alteration of areas?", "answer": "Article 3"},
    {"question": "Which body hears election disputes related to Parliamentary elections?", "answer": "High Court"},
    {"question": "The doctrine of 'Pleasure' of the President means?", "answer": "Some post-holders serve at the pleasure of the President"},
    {"question": "The Union List, State List, and Concurrent List are part of which schedule?", "answer": "Seventh Schedule"},
    {"question": "Which article defines the duties of citizens of India?", "answer": "Article 51A"},
    {"question": "The Right to Form Associations/Unions is guaranteed under?", "answer": "Article 19(1)(c)"},
    {"question": "Which article of the Indian Constitution deals with the Right to Equality?", "answer": "Article 14"},
    {"question": "The 'Collegium system' for appointment of judges derives from?", "answer": "Supreme Court judgments - Second Judges Case (1993)"},
    {"question": "The National Human Rights Commission is headed by?", "answer": "A retired Chief Justice of India"},
    {"question": "Which amendment of the Constitution increased the strength of the Supreme Court Judges to 34?", "answer": "No formal amendment; changed by Parliamentary Act"},
    {"question": "Which article allows the President to refer a matter to the Supreme Court for its opinion?", "answer": "Article 143"},
    {"question": "The Directive Principles of State Policy under Article 38 aims at?", "answer": "Securing a social order for promotion of welfare of people"},
    {"question": "The idea of 'Economic Justice' in the Constitution comes from?", "answer": "Socialist ideology incorporated in the Preamble"},
    {"question": "The first Law Minister of India was?", "answer": "Dr. B.R. Ambedkar"},
    {"question": "Which article of the Indian Constitution deals with freedom of movement?", "answer": "Article 19(1)(d)"},
    {"question": "The President of India has power to appoint which of the following?", "answer": "Governors, CAG, Attorney General, CEC"},
    {"question": "Which is the 'parent act' of the GST in India?", "answer": "Constitution (101st Amendment) Act, 2016"},
    {"question": "Under what article can the Parliament create a new All India Service?", "answer": "Article 312"},
    {"question": "The concept of 'Contempt of Court' in India falls under?", "answer": "Article 129"},
    {"question": "The 'National Financial Reporting Authority' (NFRA) was established to regulate?", "answer": "Auditing standards"},
    {"question": "Who is the supreme authority of a State Executive?", "answer": "Governor"},
    {"question": "Which amendment of the Constitution added the word 'Integrity' to the Preamble?", "answer": "42nd Amendment"},
    {"question": "The Autonomous Hill Councils in Meghalaya are provided for in which schedule?", "answer": "Sixth Schedule"},
    {"question": "Which article gives Parliament the power to legislate on State subjects under emergency?", "answer": "Article 250"},
    {"question": "The First Schedule of the Indian Constitution contains?", "answer": "Names of States and Union Territories"},
    {"question": "Which article deals with the financial powers of Parliament?", "answer": "Article 114"},
    {"question": "The Right to vote is a right established by?", "answer": "Article 326"},
    {"question": "Who has the power to grant clemency to a death row convict?", "answer": "President or Governor"},
    {"question": "The 'State' as defined in Article 12 includes?", "answer": "Central Government, State Governments, Parliament, and State Legislatures"},
    {"question": "Which schedule has provisions for administration of Scheduled Areas?", "answer": "Fifth Schedule"},
    {"question": "The term 'Sovereign' in the Preamble means?", "answer": "India is free from external control"},
    {"question": "Which article of the Constitution relates to 'Public Interest Litigation'?", "answer": "Articles 32 and 226 (PIL is a judicial creation)"},
    {"question": "Who has the power to enlarge the jurisdiction of the Supreme Court?", "answer": "Parliament"},
    {"question": "The state legislative assembly is also called?", "answer": "Vidhan Sabha"},
    {"question": "Who was the first President of India?", "answer": "Dr. Rajendra Prasad"},
    {"question": "How many subjects are in the State List?", "answer": "66 subjects"},
    {"question": "What is the term 'Prorogation of Parliament'?", "answer": "When the President terminates a session of Parliament"},
    {"question": "The Schedules 5 and 6 of the Indian Constitution deal with?", "answer": "Scheduled and Tribal areas"},
    {"question": "Which year is the Constitution of India effective from?", "answer": "January 26, 1950"},
    {"question": "Which committee gave recommendations on Panchayati Raj in 1957?", "answer": "Balwantray Mehta Committee"},
    {"question": "The anti-defection law applies to which persons?", "answer": "Members of Parliament and State Legislatures"},
    {"question": "Which High Court has the most territorial jurisdiction?", "answer": "Gauhati High Court"},
    {"question": "What is the 'Bicameral Legislature'?", "answer": "Legislature with two houses"},
    {"question": "Who conducts elections to the Council of States (Rajya Sabha)?", "answer": "Election Commission of India"},
    {"question": "Which committee made recommendations on Centre-State relations and is associated with federalism?", "answer": "Sarkaria Commission"},
    {"question": "The Rajya Sabha was established on?", "answer": "3 April 1952"},
    {"question": "Who is the Legal Advisor of the State Government?", "answer": "Advocate General"},
    {"question": "When the Rajya Sabha rejects a Money Bill, the deadlock is resolved by?", "answer": "Lok Sabha's decision prevails"},
    {"question": "Which commission is constituted every 5 years to review revenue sharing between Centre and States?", "answer": "Finance Commission"},
    {"question": "How many Fundamental Duties are listed in the Indian Constitution?", "answer": "11"},
    {"question": "The President can declare Emergency under Article 352 if there is?", "answer": "War, external aggression, or armed rebellion"},
    {"question": "Which amendment reduced the term of President's Rule from one year to six months?", "answer": "44th Amendment"},
    {"question": "Which article deals with the Right against exploitation of children?", "answer": "Article 24"},
    {"question": "The original Constitution of India had how many parts?", "answer": "22 parts"},
    {"question": "Which article provides for the allocation of seats to States in the Lok Sabha?", "answer": "Article 81"},
    {"question": "Who can initiate the Impeachment of the President?", "answer": "Either House of Parliament"},
    {"question": "Which schedule was added by 97th Constitutional Amendment related to cooperatives?", "answer": "No new schedule; it modified Part IX B"},
    {"question": "Which article deals with the composition of the Joint Public Service Commission?", "answer": "Article 315"},
    {"question": "Which tribunal hears disputes related to army?", "answer": "Armed Forces Tribunal"},
    {"question": "The 104th Amendment to the Constitution abolished?", "answer": "Reservation of seats for Anglo-Indians in Lok Sabha and State Assemblies"},
    {"question": "Which article gives power to legislature to determine qualification of Members?", "answer": "Article 102"},
    {"question": "Under what circumstances can the President exercise veto power?", "answer": "When assent to a Bill is given, withheld, or returned for reconsideration"},
    {"question": "The concept of 'Jus Soli' means citizenship by?", "answer": "Birth on the soil of a country"},
    {"question": "The 'Janata Party' government introduced which major Constitutional Amendment?", "answer": "44th Amendment"},
    {"question": "Who has the power to remove the CAG?", "answer": "President on an address by Parliament"},
    {"question": "The National Emergency of 1975 was proclaimed under which article?", "answer": "Article 352"},
    {"question": "Which article in Indian Constitution corresponds to 'Equality of opportunity in Public Employment'?", "answer": "Article 16"},
    {"question": "The 'Integrated Child Development Services' (ICDS) falls under which DPSP?", "answer": "Article 45 (early childhood care)"},
    {"question": "Under which schedule are languages recognized by the Constitution?", "answer": "Eighth Schedule"},
    {"question": "The concept of 'Residuary Powers' is borrowed from?", "answer": "Canada"},
    {"question": "The constitutional amendment bill must be passed by?", "answer": "At least 2/3 majority of members present and voting + majority of total membership"},
    {"question": "Which article of the Constitution abolishes bonded labor?", "answer": "Article 23"},
    {"question": "Who among the following cannot practice as a private advocate after leaving office?", "answer": "Attorney General of India"},
    {"question": "Under which article are Gram Panchayats established?", "answer": "Article 243(B)"},
    {"question": "The Lokayukta is a?", "answer": "State-level anti-corruption ombudsman"},
    {"question": "Which article deals with Prevention of traffic in human beings?", "answer": "Article 23"},
    {"question": "The concept of 'Locus Standi' in PIL means?", "answer": "Any citizen can file a case in public interest"},
    {"question": "Who presides over the Rajya Sabha in the absence of the Vice President?", "answer": "Deputy Chairman of Rajya Sabha"},
    {"question": "The Indian Parliament is unicameral in?", "answer": "The Centre is bicameral; some states have unicameral legislatures"},
    {"question": "Which constitutional body is responsible for recommending promotion of Hindi?", "answer": "Official Language Commission"},
    {"question": "The Conduct of Elections Rules is framed under?", "answer": "Representation of the People Act, 1951"},
    {"question": "The National Commission for Scheduled Castes derives its powers from?", "answer": "Article 338"},
    {"question": "Which article allows minorities to maintain their religious institutions?", "answer": "Article 29"},
    {"question": "Preventive Detention is permitted under which article?", "answer": "Article 22"},
    {"question": "The word 'Republic' in the Preamble signifies that?", "answer": "The head of state is elected, not hereditary"},
    {"question": "Which organisation can be approached for international arbitration?", "answer": "ICJ and ICSID"},
    {"question": "Article 51A was inserted by which Amendment Act?", "answer": "42nd Amendment"},
    {"question": "'Double Jeopardy' protection is under which article?", "answer": "Article 20(2)"},
    {"question": "The Eleventh Schedule relates to?", "answer": "Panchayati Raj (29 subjects)"},
    {"question": "The Twelfth Schedule relates to?", "answer": "Municipalities (18 subjects)"},
    {"question": "What is 'Proportional Representation' in election?", "answer": "Electoral system where parties gain representation proportional to votes"},
    {"question": "The Article 21A was inserted by which Amendment?", "answer": "86th Constitutional Amendment"},
    {"question": "The number of subjects in the Concurrent List is?", "answer": "52 subjects"},
    {"question": "Which article provides for the procedure for presentation of Budget?", "answer": "Article 112"},
    {"question": "The High Court can be established under which article?", "answer": "Article 214"},
    {"question": "The constitutional status of district courts is derived from?", "answer": "Article 235"},
    {"question": "Which article provides for the election of the Speaker of Lok Sabha?", "answer": "Article 93"},
    {"question": "Special Courts for trying cases related to electoral disputes are established under?", "answer": "Acts passed by Parliament"},
    {"question": "The 'People's House' of India is?", "answer": "Lok Sabha"},
    {"question": "Who was the first Vice President of India?", "answer": "S. Radhakrishnan"},
    {"question": "The term 'Federal' does not appear in the Indian Constitution; India is called?", "answer": "Union of States"},
    {"question": "The power to remove a judge of the Supreme Court is with?", "answer": "President on an address by Parliament"},
    {"question": "Under which article does the Union levy taxes?", "answer": "Articles 265 to 287"},
    {"question": "Which body recommends division of taxes between Centre and States?", "answer": "Finance Commission"},
    {"question": "The First Amendment to the Indian Constitution was enacted in?", "answer": "1951"},
    {"question": "The Rajya Sabha has to pass a Money Bill within?", "answer": "14 days"},
    {"question": "Which article deals with the right to property?", "answer": "Article 300A (as a legal right)"},
    {"question": "Indian Parliament includes?", "answer": "President, Rajya Sabha, and Lok Sabha"},
    {"question": "The National Commission for Scheduled Tribes derives its powers from?", "answer": "Article 338A"},
    {"question": "'Star Questions' in Indian Parliament require?", "answer": "Oral answers by Ministers"},
    {"question": "Under which article can Parliament impose restrictions on trade?", "answer": "Article 19(6)"},
    {"question": "The original jurisdiction of the Supreme Court includes?", "answer": "Disputes between different States"},
    {"question": "The doctrine of 'Severability' in constitutional law means?", "answer": "Only the unconstitutional part of a law is struck down, not the whole"},
    {"question": "Which amendment gave constitutional status to cooperatives?", "answer": "97th Constitutional Amendment"},
    {"question": "Who was India's first Female President?", "answer": "Pratibha Patil"},
    {"question": "Which is the highest court of appeal in India?", "answer": "Supreme Court of India"},
    {"question": "The concept of 'Economic Justice' in the Preamble was borrowed from?", "answer": "Russian Revolution (socialist ideology)"},
    {"question": "UPSC recommendations for civil services are made to?", "answer": "President of India"},
    {"question": "Which article provides for a Consolidated Fund of India?", "answer": "Article 266"},
    {"question": "The Rajya Sabha can delay a Money Bill by maximum?", "answer": "14 days"},
    {"question": "Which amendment restricted ownership of property by Parliament?", "answer": "44th Amendment (deleted Right to Property from Fundamental Rights)"},
    {"question": "Which article allows Parliament to modify state boundaries?", "answer": "Article 3"},
    {"question": "The Constitution uses the term 'citizens' in which context?", "answer": "For fundamental rights and voting"},
    {"question": "The Atal Bihari Vajpayee government passed the 86th Amendment for?", "answer": "Right to Education"},
    {"question": "India is classified as a 'Democratic Republic' which means?", "answer": "Representatives are elected by the people"},
    {"question": "The 'Directive Principles' are classified under which category?", "answer": "Non-justiciable but fundamental to governance"},
    {"question": "What is meant by 'Extradition' in international law?", "answer": "Transfer of a person accused of a crime to another country"},
    {"question": "Which article grants power to Parliament to amend the Constitution?", "answer": "Article 368"},
    {"question": "Article 300A relates to?", "answer": "Right to Property (as legal right)"},
    {"question": "What is the 'Money Bill' clause under the Indian Constitution?", "answer": "Article 110"},
    {"question": "Which article deals with the Parliamentary privileges?", "answer": "Articles 105 and 194"},
    {"question": "Which body recommends delimitation of Parliamentary and Assembly constituencies?", "answer": "Delimitation Commission"},
    {"question": "How many members are there in the Constituent Assembly which drafted the Indian Constitution?", "answer": "299"},
    {"question": "The word 'Fraternity' in the Preamble was inspired by?", "answer": "The French Revolution"},
    {"question": "Which part of the Indian Constitution is called the 'Soul of the Constitution'?", "answer": "Part III (Fundamental Rights)"},
    {"question": "The Governor of a State can reserve a Bill for the consideration of the?", "answer": "President"},
    {"question": "Which article defines the territorial limits of the Indian States?", "answer": "Article 1 (India= Bharat, Union of States)"},
    {"question": "What is the 'Doctrine of Necessity' in constitutional law?", "answer": "An exception allowing actions that would otherwise be unconstitutional"},
    {"question": "Under which article is the National Commission for Backward Classes constituted?", "answer": "Article 338B"},
    {"question": "Which article allows the President to appoint Governors of States?", "answer": "Article 155"},
    {"question": "The Union PSC was established under?", "answer": "Article 315"},
    {"question": "How many members of Rajya Sabha retire every second year?", "answer": "One-third"},
    {"question": "Under which schedule is the PESA Act related?", "answer": "Fifth Schedule"},
    {"question": "Who certifies that a Bill is a Money Bill?", "answer": "Speaker of Lok Sabha"},
    {"question": "The Constitutional Amendments can also be made by which Article?", "answer": "Article 368"},
    {"question": "Which article of the Constitution confers original jurisdiction on the Supreme Court for enforcement of fundamental rights?", "answer": "Article 32"},
    {"question": "The concept of 'Organic Law' means?", "answer": "A law of fundamental importance, relating to the basic structure of the state"},
    {"question": "Under which article can Parliament legislate on subjects in the State List during a National Emergency?", "answer": "Article 250"},
    {"question": "Who administers the oath of secrecy to the Cabinet Ministers?", "answer": "President"},
    {"question": "The Emergency provisions in India are contained in?", "answer": "Articles 352 to 360"},
    {"question": "By virtue of which article is the Prime Minister appointed?", "answer": "Article 75"},
    {"question": "Which amendment added 'Fundamental Duties' to the Constitution?", "answer": "42nd Amendment, 1976"},
    {"question": "The 'Doctrine of Pleasure' in India means the President has absolute power to dismiss?", "answer": "No; dismissal must follow procedure established by law"},
    {"question": "Which article provides for the right to hold religious ceremonies?", "answer": "Article 25"},
    {"question": "How many members of Lok Sabha are directly elected?", "answer": "543"},
    {"question": "The Union Territories are administered by?", "answer": "President through Administrator or Lieutenant Governor"},
    {"question": "From which country was the idea of a unicameral legislature at state level borrowed?", "answer": "The USA (though India allows both)"},
    {"question": "Who has power to legislate on Entry 97 of the Union List?", "answer": "Parliament of India"},
    {"question": "The Rajya Sabha was first constituted on?", "answer": "3 April 1952"},
    {"question": "Which article deals with Equality of Status in the Preamble?", "answer": "The Preamble itself embodies it; Article 14 in fundamental rights"},
    {"question": "No. of languages in the 8th Schedule of Indian Constitution is?", "answer": "22"},
    {"question": "What is meant by 'Martial Law' in constitutional context?", "answer": "Temporary military rule during emergency"},
    {"question": "Under which article can the President remove the Governor from office?", "answer": "Article 156 (Governor holds office at pleasure of President)"},
    {"question": "The Legislative Council of the State is also called?", "answer": "Vidhan Parishad"},
    {"question": "Under which article is the Consolidated Fund of India established?", "answer": "Article 266"},
    {"question": "Article 226 of the Constitution gives which court power to issue writs?", "answer": "High Court"},
    {"question": "The 'Caste' discrimination is prohibited under?", "answer": "Article 15(1)"},
    {"question": "Which article makes 'equal justice and free legal aid' a DPSP?", "answer": "Article 39A"},
    {"question": "The Attorney General of India can practice in any court in India. This right comes from?", "answer": "Article 76"},
    {"question": "Which article provides for the Right against Exploitation?", "answer": "Articles 23 and 24"},
    {"question": "Who presides over a joint sitting called to resolve a deadlock between the two Houses?", "answer": "Speaker of Lok Sabha"},
    {"question": "The National Emergency declared in 1962 was due to?", "answer": "Chinese aggression"},
    {"question": "'Judicial Activism' in India is reflected by which concept?", "answer": "Public Interest Litigation (PIL)"},
    {"question": "Who was the first CJI of India?", "answer": "Justice HJ Kania"},
    {"question": "The concept of 'Due Process of Law' was adopted in India from?", "answer": "USA"},
    {"question": "Under Article 74, the President must act in accordance with?", "answer": "Advice of the Council of Ministers headed by the PM"},
    {"question": "Which article makes the Right to Education a Fundamental Right?", "answer": "Article 21A"},
    {"question": "The 'Sunset Clause' is commonly associated with?", "answer": "Laws of limited duration"},
    {"question": "Which Amendment introduced the National Judicial Appointments Commission (NJAC)?", "answer": "99th Amendment (declared unconstitutional)"},
    {"question": "Which article deals with the promotion of international peace and security?", "answer": "Article 51"},
    {"question": "The Government of India Act, 1935 provided for?", "answer": "Federal Government at Centre and Provincial Autonomy"},
    {"question": "Who can dissolve the Rajya Sabha?", "answer": "Nobody; it is a permanent house"},
    {"question": "Which article regulates the relations of trade and commerce?", "answer": "Articles 301 to 307"},
    {"question": "The 'Golden Triangle' of Fundamental Rights includes?", "answer": "Articles 14, 19, and 21"},
    {"question": "The 'Dharna' (sit-in protest) is related to which Fundamental Right?", "answer": "Article 19(1)(b) - Freedom of Assembly"},
]

# --- Add more geography ---
extra_geo_10 = [
    {"question": "Which is the longest river in Russia?", "answer": "Ob River"},
    {"question": "What is the capital of Mongolia?", "answer": "Ulaanbaatar"},
    {"question": "The Bosporus strait separates which city between two continents?", "answer": "Istanbul"},
    {"question": "Which country has the most time zones?", "answer": "France"},
    {"question": "The Dead Sea is located between which two countries?", "answer": "Israel and Jordan"},
    {"question": "Which is the shallowest ocean?", "answer": "Arctic Ocean"},
    {"question": "What is the capital of Kazakhstan?", "answer": "Astana"},
    {"question": "The area of North America is approximately?", "answer": "24.7 million sq km"},
    {"question": "Which city is known as the 'City of Seven Hills'?", "answer": "Rome"},
    {"question": "The Yellow River is also known as?", "answer": "Huang He"},
]

extra_eco_20 = [
    {"question": "What is 'Aggregate Demand'?", "answer": "Total demand for goods and services in an economy"},
    {"question": "The term 'Velocity of Money' refers to?", "answer": "Rate at which money circulates in an economy"},
    {"question": "Which bank in India is known as the 'banker's bank'?", "answer": "Reserve Bank of India"},
    {"question": "The first Five Year Plan of India was implemented in?", "answer": "1951-56"},
    {"question": "Which index measures cost of living for workers?", "answer": "Consumer Price Index for Industrial Workers (CPI-IW)"},
    {"question": "What is 'Minimum Support Price' (MSP)?", "answer": "Guaranteed price at which the government buys farmer produce"},
    {"question": "The term 'Fiscal Federalism' refers to?", "answer": "Division of financial relations between Centre and States"},
    {"question": "Which is the largest public sector bank in India?", "answer": "State Bank of India (SBI)"},
    {"question": "The term 'Disinflation' means?", "answer": "Reduction in the rate of inflation"},
    {"question": "The National Income of India is estimated by?", "answer": "Central Statistics Office (CSO)"},
    {"question": "India's largest trading partner as of recent years is?", "answer": "USA"},
    {"question": "The concept of 'Economic Rent' was given by?", "answer": "David Ricardo"},
    {"question": "What does 'CAMELS' stand for in banking?", "answer": "Capital, Assets, Management, Earnings, Liquidity, Sensitivity"},
    {"question": "The term 'Hot Money' refers to?", "answer": "Capital that moves quickly between countries seeking best returns"},
    {"question": "Which tax is levied on goods produced within a country?", "answer": "Excise duty"},
    {"question": "The term 'Fiscal Drag' occurs when?", "answer": "Inflation pushes incomes into higher tax brackets"},
    {"question": "What is 'Repo Rate'?", "answer": "Rate at which RBI lends money to commercial banks"},
    {"question": "The 'Pink Sheet' in economics refers to?", "answer": "OTC (Over-the-counter) market for securities"},
    {"question": "Which is the oldest stock exchange in India?", "answer": "Bombay Stock Exchange (BSE) - 1875"},
    {"question": "The 'Hawala' transaction is an example of?", "answer": "Informal money transfer system"},
]

# Add extra geography
existing_geo = data['geography']
needed = 500 - len(existing_geo)
existing_q_strs = {q['question'] for q in existing_geo}
all_extra_geo = extra_geo_10
for q in all_extra_geo:
    if needed <= 0:
        break
    if q['question'] not in existing_q_strs:
        existing_geo.append({"id": len(existing_geo)+1, "question": q['question'], "answer": q['answer']})
        existing_q_strs.add(q['question'])
        needed -= 1
data['geography'] = existing_geo

# Add polity questions
existing_polity = data['polity']
existing_polity_strs = {q['question'] for q in existing_polity}
needed_polity = 500 - len(existing_polity)
for q in polity_qs:
    if needed_polity <= 0:
        break
    if q['question'] not in existing_polity_strs:
        existing_polity.append({"id": len(existing_polity)+1, "question": q['question'], "answer": q['answer']})
        existing_polity_strs.add(q['question'])
        needed_polity -= 1
data['polity'] = existing_polity

# Add extra economy
existing_eco = data['economy']
existing_eco_strs = {q['question'] for q in existing_eco}
needed_eco = 500 - len(existing_eco)
for q in extra_eco_20:
    if needed_eco <= 0:
        break
    if q['question'] not in existing_eco_strs:
        existing_eco.append({"id": len(existing_eco)+1, "question": q['question'], "answer": q['answer']})
        existing_eco_strs.add(q['question'])
        needed_eco -= 1
data['economy'] = existing_eco

# Final counts
for topic, qs in data.items():
    print(f"{topic}: {len(qs)} questions")

js = f"const questions_upsc = {json.dumps(data, indent=2)};\n"
open('questions_upsc.js', 'w', encoding='utf-8').write(js)
print("Done! Written to questions_upsc.js")
