import json, re

# Load existing file
text = open('questions_upsc.js', encoding='utf-8').read()
data = json.loads(re.sub(r'^const questions_upsc = ', '', text).rstrip(';\n'))

# ---- Additional Geography Questions (200 unique) ----
extra_geography = [
    {"question": "Which is the highest plateau in the world?", "answer": "Tibetan Plateau"},
    {"question": "The Strait of Gibraltar connects which two bodies of water?", "answer": "Atlantic Ocean and Mediterranean Sea"},
    {"question": "Which country has the most natural lakes?", "answer": "Canada"},
    {"question": "The Amazon River flows through which continent?", "answer": "South America"},
    {"question": "Which is the smallest ocean in the world?", "answer": "Arctic Ocean"},
    {"question": "What is the capital of Canada?", "answer": "Ottawa"},
    {"question": "Which is the longest river in Africa?", "answer": "Nile"},
    {"question": "The Dead Sea is located in which region?", "answer": "Middle East"},
    {"question": "Which mountain range separates Europe from Asia?", "answer": "Ural Mountains"},
    {"question": "The Nile River flows into which sea?", "answer": "Mediterranean Sea"},
    {"question": "Which country has the largest population in the world?", "answer": "India"},
    {"question": "What is the capital of Brazil?", "answer": "Brasília"},
    {"question": "Which is the longest river in South America?", "answer": "Amazon"},
    {"question": "The Atacama Desert is located in which country?", "answer": "Chile"},
    {"question": "What is the capital of Argentina?", "answer": "Buenos Aires"},
    {"question": "Which ocean lies between Europe and America?", "answer": "Atlantic Ocean"},
    {"question": "What is the capital of China?", "answer": "Beijing"},
    {"question": "Which country has the longest coastline in the world?", "answer": "Canada"},
    {"question": "The Atlas Mountains are located in which continent?", "answer": "Africa"},
    {"question": "Which is the smallest country in the world?", "answer": "Vatican City"},
    {"question": "Lake Victoria is shared by which countries?", "answer": "Kenya, Uganda, and Tanzania"},
    {"question": "Which peninsula is India part of?", "answer": "Indian Peninsula"},
    {"question": "Which river forms the boundary between India and Pakistan?", "answer": "Ravi"},
    {"question": "The Tropic of Cancer passes through how many Indian states?", "answer": "8"},
    {"question": "Which is the largest river island in India?", "answer": "Majuli"},
    {"question": "The Eastern Ghats and Western Ghats meet at which hills?", "answer": "Nilgiri Hills"},
    {"question": "Which is the coldest inhabited place on Earth?", "answer": "Oymyakon, Russia"},
    {"question": "Which country is entirely surrounded by South Africa?", "answer": "Lesotho"},
    {"question": "The Mediterranean Sea is connected to the Red Sea by?", "answer": "Suez Canal"},
    {"question": "The Gobi Desert lies in which country?", "answer": "Mongolia and China"},
    {"question": "Which is the largest lake in Africa?", "answer": "Lake Victoria"},
    {"question": "The Bering Strait separates which two countries?", "answer": "Russia and USA"},
    {"question": "What is the capital of Japan?", "answer": "Tokyo"},
    {"question": "Which is the highest mountain in Africa?", "answer": "Mount Kilimanjaro"},
    {"question": "What is the capital of Germany?", "answer": "Berlin"},
    {"question": "Which is the longest mountain range in Asia?", "answer": "Himalayas"},
    {"question": "The Panama Canal connects which two oceans?", "answer": "Atlantic and Pacific"},
    {"question": "What is the capital of Italy?", "answer": "Rome"},
    {"question": "Which country is known as the 'Land of Midnight Sun'?", "answer": "Norway"},
    {"question": "Which country has the largest land area in Africa?", "answer": "Algeria"},
    {"question": "What is the capital of South Africa's legislative capital?", "answer": "Cape Town"},
    {"question": "Which is the deepest lake in the world?", "answer": "Lake Baikal"},
    {"question": "The Sahara Desert covers most of which continent?", "answer": "Africa"},
    {"question": "Which country is the largest producer of coffee?", "answer": "Brazil"},
    {"question": "The volcano Krakatoa is located in which country?", "answer": "Indonesia"},
    {"question": "What is the capital of Egypt?", "answer": "Cairo"},
    {"question": "Mount Etna is a volcano located in which country?", "answer": "Italy"},
    {"question": "The Yangtze River flows through which country?", "answer": "China"},
    {"question": "Which is the smallest country in Asia?", "answer": "Maldives"},
    {"question": "What is the capital of Pakistan?", "answer": "Islamabad"},
    {"question": "The Danube River flows through how many countries?", "answer": "10"},
    {"question": "Which is the tallest building in the world as of 2020?", "answer": "Burj Khalifa"},
    {"question": "What is the capital of Spain?", "answer": "Madrid"},
    {"question": "Which country is home to the Amazon rainforest?", "answer": "Brazil"},
    {"question": "The island of Greenland belongs to which country?", "answer": "Denmark"},
    {"question": "What is the capital of New Zealand?", "answer": "Wellington"},
    {"question": "Which is the largest country in South America?", "answer": "Brazil"},
    {"question": "The Black Sea is surrounded by which countries?", "answer": "Turkey, Bulgaria, Romania, Ukraine, Russia, Georgia"},
    {"question": "What is the capital of South Korea?", "answer": "Seoul"},
    {"question": "Which country is called the 'Pearl of Africa'?", "answer": "Uganda"},
    {"question": "The Mount Logan is the highest peak of which country?", "answer": "Canada"},
    {"question": "What is the capital of Turkey?", "answer": "Ankara"},
    {"question": "Which country is known as the 'Land of Thunder Dragon'?", "answer": "Bhutan"},
    {"question": "The Straits of Malacca lie between which countries?", "answer": "Malaysia and Indonesia"},
    {"question": "What is the currency of Japan?", "answer": "Yen"},
    {"question": "Which is the largest island in the world?", "answer": "Greenland"},
    {"question": "What is the capital of Mexico?", "answer": "Mexico City"},
    {"question": "The Ganges River originates from which glacier?", "answer": "Gangotri Glacier"},
    {"question": "Which country is the world's largest producer of rubber?", "answer": "Thailand"},
    {"question": "The Suez Canal is located in which country?", "answer": "Egypt"},
    {"question": "Which is the world's longest river?", "answer": "Nile"},
    {"question": "What is the capital of Indonesia?", "answer": "Jakarta"},
    {"question": "The Victoria Falls is located on the border of which two countries?", "answer": "Zimbabwe and Zambia"},
    {"question": "Which is the largest country in Africa?", "answer": "Algeria"},
    {"question": "What is the capital of Saudi Arabia?", "answer": "Riyadh"},
    {"question": "Which country is called the 'Land of the Free'?", "answer": "USA"},
    {"question": "The Nanga Parbat peak is located in which country?", "answer": "Pakistan"},
    {"question": "What is the capital of Nigeria?", "answer": "Abuja"},
    {"question": "Which continent is also a country?", "answer": "Australia"},
    {"question": "The Mekong River flows through how many countries?", "answer": "6"},
    {"question": "What is the capital of Iran?", "answer": "Tehran"},
    {"question": "Which is the longest river in Europe?", "answer": "Volga"},
    {"question": "The Krakatau volcano is located in which country?", "answer": "Indonesia"},
    {"question": "What is the capital of Bangladesh?", "answer": "Dhaka"},
    {"question": "Which country has the most earthquakes per year?", "answer": "Japan"},
    {"question": "Lake Superior is located on the border between which two countries?", "answer": "USA and Canada"},
    {"question": "Which is the largest gulf in the world?", "answer": "Gulf of Mexico"},
    {"question": "What is the capital of Sweden?", "answer": "Stockholm"},
    {"question": "The Orinoco River is located in which country?", "answer": "Venezuela"},
    {"question": "Which is the world's highest navigable lake?", "answer": "Lake Titicaca"},
    {"question": "What is the capital of France?", "answer": "Paris"},
    {"question": "Which country has the most volcanoes?", "answer": "Indonesia"},
    {"question": "The Pyrenees mountains form the border between which two countries?", "answer": "France and Spain"},
    {"question": "What is the capital of Russia?", "answer": "Moscow"},
    {"question": "Which is the smallest continent?", "answer": "Australia"},
    {"question": "The Zambezi River flows into which ocean?", "answer": "Indian Ocean"},
    {"question": "What is the capital of India?", "answer": "New Delhi"},
    {"question": "Which country has the Sahara Desert on its territory?", "answer": "Algeria"},
    {"question": "The Ring of Fire is associated with what geological activity?", "answer": "Volcanic eruptions and earthquakes"},
    {"question": "What is the capital of Portugal?", "answer": "Lisbon"},
    {"question": "Which is the highest waterfall in Asia?", "answer": "Nohkalikai Falls, India"},
    {"question": "The Caspian Sea is the world's largest what?", "answer": "Inland body of water"},
    {"question": "What is the capital of Switzerland?", "answer": "Bern"},
    {"question": "The Great Rift Valley runs through which continent?", "answer": "Africa"},
    {"question": "Which is the largest city in Africa by population?", "answer": "Lagos"},
    {"question": "What is the capital of the Netherlands?", "answer": "Amsterdam"},
    {"question": "The Rocky Mountains are located in which country?", "answer": "USA"},
    {"question": "Which ocean is the warmest?", "answer": "Indian Ocean"},
    {"question": "What is the capital of Poland?", "answer": "Warsaw"},
    {"question": "The country of Chile is located in which continent?", "answer": "South America"},
    {"question": "Which is the largest lake in North America?", "answer": "Lake Superior"},
    {"question": "What is the capital of Ukraine?", "answer": "Kyiv"},
    {"question": "The Indus River originates from which country?", "answer": "China"},
    {"question": "Which sea is the saltiest in the world?", "answer": "Dead Sea"},
    {"question": "What is the capital of Czech Republic?", "answer": "Prague"},
    {"question": "The Sahara Desert is approximately which size?", "answer": "9.2 million sq km"},
    {"question": "Which is the windiest place on Earth?", "answer": "Antarctica"},
    {"question": "What is the capital of Greece?", "answer": "Athens"},
    {"question": "The Congo River is the deepest river in which continent?", "answer": "Africa"},
    {"question": "Which island group includes Sumatra, Java, and Borneo?", "answer": "Indonesian Archipelago"},
    {"question": "What is the capital of Norway?", "answer": "Oslo"},
    {"question": "Which is the most densely populated country in the world?", "answer": "Monaco"},
    {"question": "The Arctic Ocean is the world's smallest and shallowest ocean?", "answer": "True"},
    {"question": "What is the capital of Denmark?", "answer": "Copenhagen"},
    {"question": "The Himalayas lie along the border of how many countries?", "answer": "5"},
    {"question": "Which country has the most deserts?", "answer": "Australia"},
    {"question": "What is the capital of Finland?", "answer": "Helsinki"},
    {"question": "The Maldives is the smallest country by which measure?", "answer": "Land area in Asia"},
    {"question": "Which is the tallest mountain in North America?", "answer": "Denali"},
    {"question": "What is the capital of Belgium?", "answer": "Brussels"},
    {"question": "The Amazon Basin is the largest what in the world?", "answer": "Tropical rainforest"},
    {"question": "Which country has the most number of UNESCO World Heritage Sites?", "answer": "Italy"},
    {"question": "What is the capital of Austria?", "answer": "Vienna"},
    {"question": "The Caribbean Sea is located in which ocean basin?", "answer": "Atlantic"},
    {"question": "Which is the smallest state of India by area?", "answer": "Goa"},
    {"question": "What is the capital of Hungary?", "answer": "Budapest"},
    {"question": "The Sundarbans is the world's largest mangrove forest located in which countries?", "answer": "India and Bangladesh"},
    {"question": "Which is the highest peak in the Himalayas?", "answer": "Mount Everest"},
    {"question": "What is the capital of Romania?", "answer": "Bucharest"},
    {"question": "The Yangtze River is the longest river in which country?", "answer": "China"},
    {"question": "Which is the hottest continent?", "answer": "Africa"},
    {"question": "What is the capital of Serbia?", "answer": "Belgrade"},
    {"question": "The Tigris and Euphrates rivers are located in which region?", "answer": "Middle East"},
    {"question": "Which country is separated from Africa by the Strait of Gibraltar?", "answer": "Spain"},
    {"question": "What is the capital of Croatia?", "answer": "Zagreb"},
    {"question": "The Amazon River delta is located in which country?", "answer": "Brazil"},
    {"question": "Which is the highest peak in South America?", "answer": "Aconcagua"},
    {"question": "What is the capital of Slovakia?", "answer": "Bratislava"},
    {"question": "Which is the driest hot desert?", "answer": "Atacama Desert"},
    {"question": "The Mariana Trench is located in which ocean?", "answer": "Pacific Ocean"},
    {"question": "What is the capital of Bulgaria?", "answer": "Sofia"},
    {"question": "The Nile River passes through how many countries?", "answer": "11"},
    {"question": "Which country has the Serengeti National Park?", "answer": "Tanzania"},
    {"question": "What is the capital of Lithuania?", "answer": "Vilnius"},
    {"question": "The Great Wall of China was built primarily along which feature?", "answer": "Northern border of China"},
    {"question": "Which country has the most indigenous language groups?", "answer": "Papua New Guinea"},
    {"question": "What is the capital of Latvia?", "answer": "Riga"},
    {"question": "What is the most common type of soil in India?", "answer": "Alluvial soil"},
    {"question": "Which is the largest delta in the world?", "answer": "Ganges-Brahmaputra Delta"},
    {"question": "What is the capital of Estonia?", "answer": "Tallinn"},
    {"question": "The Irawaddy River flows through which country?", "answer": "Myanmar"},
    {"question": "Which is the largest salt lake in the world?", "answer": "Caspian Sea"},
    {"question": "What is the capital of Iceland?", "answer": "Reykjavik"},
    {"question": "The Kalahari Desert is located in which continent?", "answer": "Africa"},
    {"question": "Which is the highest unclimbed mountain in the world?", "answer": "Gangkhar Puensum"},
    {"question": "What is the capital of Israel?", "answer": "Jerusalem"},
    {"question": "The Volga River flows into which sea?", "answer": "Caspian Sea"},
    {"question": "Which is the largest river in India by discharge?", "answer": "Ganga"},
    {"question": "What is the capital of Iraq?", "answer": "Baghdad"},
    {"question": "The Deccan Plateau is located in which country?", "answer": "India"},
    {"question": "Which is the highest mountain in Europe?", "answer": "Mont Blanc"},
    {"question": "What is the capital of Afghanistan?", "answer": "Kabul"},
    {"question": "The Caspian Sea borders how many countries?", "answer": "5"},
    {"question": "Which country has the largest area of glaciers outside polar regions?", "answer": "Canada"},
    {"question": "What is the capital of Nepal?", "answer": "Kathmandu"},
    {"question": "The Bay of Bengal is part of which ocean?", "answer": "Indian Ocean"},
    {"question": "Which is the longest river in North America?", "answer": "Missouri River"},
    {"question": "What is the capital of Sri Lanka?", "answer": "Sri Jayawardenepura Kotte"},
    {"question": "The Alps mountain range is shared by how many countries?", "answer": "8"},
    {"question": "Which country lies between France and Spain?", "answer": "Andorra"},
    {"question": "What is the capital of Myanmar?", "answer": "Naypyidaw"},
    {"question": "The Strait of Hormuz connects which two bodies of water?", "answer": "Persian Gulf and Gulf of Oman"},
    {"question": "Which is the highest point in Australia?", "answer": "Mount Kosciuszko"},
    {"question": "What is the capital of Vietnam?", "answer": "Hanoi"},
    {"question": "Lake Chad is located in Central Africa and is shared by how many countries?", "answer": "4"},
    {"question": "Which ocean has the most islands?", "answer": "Pacific Ocean"},
    {"question": "What is the capital of Thailand?", "answer": "Bangkok"},
    {"question": "The Vesuvius volcano is located near which city in Italy?", "answer": "Naples"},
    {"question": "Which is the easternmost country in the world?", "answer": "Kiribati"},
    {"question": "What is the capital of Malaysia?", "answer": "Kuala Lumpur"},
]

# ---- Additional Economy Questions (163 unique) ----
extra_economy = [
    {"question": "What is 'fiscal policy'?", "answer": "Government's use of taxation and spending to influence the economy"},
    {"question": "Which body regulates the capital markets in India?", "answer": "SEBI (Securities and Exchange Board of India)"},
    {"question": "What is the full form of GNP?", "answer": "Gross National Product"},
    {"question": "The term 'Bull Market' refers to?", "answer": "A market in which share prices are rising"},
    {"question": "Which country is the world's largest exporter of goods?", "answer": "China"},
    {"question": "What does IMF stand for?", "answer": "International Monetary Fund"},
    {"question": "The New Economic Policy (NEP) in India was launched in which year?", "answer": "1991"},
    {"question": "Which committee recommended the Goods and Services Tax (GST) in India?", "answer": "Kelkar Committee"},
    {"question": "Who is the regulator of the insurance sector in India?", "answer": "IRDAI"},
    {"question": "The World Trade Organization (WTO) replaced which earlier body?", "answer": "GATT"},
    {"question": "What does 'PPP' stand for in economics?", "answer": "Purchasing Power Parity"},
    {"question": "Which organization publishes the Human Development Index?", "answer": "UNDP"},
    {"question": "The term 'Bear Market' refers to?", "answer": "A market in which share prices are falling"},
    {"question": "The Sensex is related to which stock exchange?", "answer": "Bombay Stock Exchange (BSE)"},
    {"question": "What is the Nifty 50?", "answer": "Stock market index of NSE (National Stock Exchange)"},
    {"question": "Which Indian economist won the Nobel Prize in Economics in 1998?", "answer": "Amartya Sen"},
    {"question": "The World Bank is headquartered in?", "answer": "Washington, D.C."},
    {"question": "What is the full form of NPA in banking?", "answer": "Non-Performing Asset"},
    {"question": "MUDRA stands for?", "answer": "Micro Units Development and Refinance Agency"},
    {"question": "Which body recommends the distribution of taxes between Centre and States in India?", "answer": "Finance Commission"},
    {"question": "The Laffer Curve is associated with which economic concept?", "answer": "Tax rates and revenue"},
    {"question": "What is the economic term for demand that cannot be met by supply?", "answer": "Excess demand or shortage"},
    {"question": "Which country has the world's largest GDP?", "answer": "USA"},
    {"question": "The Tobin Tax is proposed on?", "answer": "Currency exchange transactions"},
    {"question": "Which Indian economist is known for the concept of 'drain of wealth'?", "answer": "Dadabhai Naoroji"},
    {"question": "What is the role of the Monetary Policy Committee (MPC) in India?", "answer": "Setting the repo rate and managing monetary policy"},
    {"question": "The Pradhan Mantri Jan Dhan Yojana is related to?", "answer": "Financial inclusion"},
    {"question": "Which body controls the monetary policy of the USA?", "answer": "Federal Reserve"},
    {"question": "What is 'Disinvestment' in economics?", "answer": "Government selling its stake in public sector enterprises"},
    {"question": "The term 'Recession' is generally defined as?", "answer": "Two consecutive quarters of negative GDP growth"},
    {"question": "What is the minimum reserve system related to?", "answer": "RBI's method of note issue"},
    {"question": "Which is the largest stock exchange by market capitalization?", "answer": "New York Stock Exchange (NYSE)"},
    {"question": "Export-Import Bank of India is also known as?", "answer": "EXIM Bank"},
    {"question": "What is Open Market Operations (OMO)?", "answer": "RBI buying/selling government securities to control liquidity"},
    {"question": "The Jan Lokpal Bill was associated with which movement?", "answer": "India Against Corruption movement"},
    {"question": "Which sector dominates Indian employment?", "answer": "Agriculture"},
    {"question": "The Kuznets Curve is related to?", "answer": "Income inequality and economic development"},
    {"question": "What is meant by 'Capital Account Convertibility'?", "answer": "Freedom to convert local currency to foreign for capital transactions"},
    {"question": "The Pradhan Mantri Gram Sadak Yojana is related to?", "answer": "Rural road construction"},
    {"question": "What is the base year for current GDP calculations in India?", "answer": "2011-12"},
    {"question": "Which industry contributes most to India's export earnings?", "answer": "Software and IT services"},
    {"question": "The TRIPS Agreement is related to?", "answer": "Trade-Related Aspects of Intellectual Property Rights"},
    {"question": "Monetary policy refers to?", "answer": "Central bank's management of money supply and interest rates"},
    {"question": "The Maastricht Treaty led to the creation of which currency?", "answer": "Euro"},
    {"question": "Who introduced the concept of the multiplier in economics?", "answer": "John Maynard Keynes"},
    {"question": "Which organization grants loans to developing countries for development?", "answer": "World Bank"},
    {"question": "The National Housing Bank (NHB) was established in which year?", "answer": "1988"},
    {"question": "What is 'Demand-pull inflation'?", "answer": "Inflation caused by excessive demand in the economy"},
    {"question": "Which component is NOT part of M1 money supply?", "answer": "Time deposits"},
    {"question": "The NABARD Act was passed in?", "answer": "1981"},
    {"question": "What is 'Sterilization' in central banking?", "answer": "Offsetting the effects of foreign exchange intervention on money supply"},
    {"question": "The Securities Appellate Tribunal (SAT) hears appeals against decisions of?", "answer": "SEBI"},
    {"question": "What is the maximum FEMA penalty in India?", "answer": "Three times the amount involved"},
    {"question": "The term 'Bottleneck Inflation' is caused by?", "answer": "Supply-side constraints"},
    {"question": "Which country introduced the concept of a Sovereign Wealth Fund?", "answer": "Kuwait"},
    {"question": "What does SDR stand for in the context of IMF?", "answer": "Special Drawing Rights"},
    {"question": "The Gini Coefficient measures?", "answer": "Income inequality"},
    {"question": "What is the 'Phillips Curve'?", "answer": "Inverse relationship between unemployment and inflation"},
    {"question": "The 'Blue Economy' refers to?", "answer": "Sustainable use of ocean resources for economic growth"},
    {"question": "Which Five Year Plan in India was called the 'Gadgil Plan'?", "answer": "Fourth Five Year Plan"},
    {"question": "The Agricultural Prices Commission (APC) was renamed as?", "answer": "Commission for Agricultural Costs and Prices (CACP)"},
    {"question": "What is 'Dead Weight Loss'?", "answer": "The loss of economic efficiency when equilibrium is not achieved"},
    {"question": "Which report ranks countries by Ease of Doing Business?", "answer": "World Bank Doing Business Report"},
    {"question": "The Narasimham Committee was related to?", "answer": "Banking sector reforms"},
    {"question": "What does EXIM stand for?", "answer": "Export and Import"},
    {"question": "India's first stock exchange was established in?", "answer": "1875 in Mumbai"},
    {"question": "The term 'Fiscal Cliff' refers to?", "answer": "Simultaneous tax increases and spending cuts"},
    {"question": "SEBI was established by an Act of Parliament in?", "answer": "1992"},
    {"question": "Which bank was nationalized first in India?", "answer": "Reserve Bank of India (RBI) in 1949"},
    {"question": "The Hawkins-Simon conditions are related to?", "answer": "Input-output analysis"},
    {"question": "What is 'Stagflation'?", "answer": "Combination of stagnant economic growth and high inflation"},
    {"question": "The Economic Survey of India is published by?", "answer": "Ministry of Finance"},
    {"question": "What is meant by 'Balance of Trade'?", "answer": "Difference between a country's exports and imports of goods"},
    {"question": "Which commission recommended the rationalization of subsidies?", "answer": "Expenditure Reform Commission"},
    {"question": "The term 'Invisible Hand' was coined by?", "answer": "Adam Smith"},
    {"question": "What is 'Trade Deficit'?", "answer": "When imports exceed exports"},
    {"question": "The Bharat Nirman Program is related to?", "answer": "Rural infrastructure development"},
    {"question": "What is 'Seigniorage'?", "answer": "Profit made by a government by issuing currency"},
    {"question": "The National Rural Employment Guarantee Act (NREGA) was enacted in?", "answer": "2005"},
    {"question": "Who was the chairman of the 14th Finance Commission?", "answer": "Y.V. Reddy"},
    {"question": "Which theory states that government spending is more effective during a recession?", "answer": "Keynesian economics"},
    {"question": "The World Economic Forum (WEF) is headquartered in?", "answer": "Davos, Switzerland"},
    {"question": "What is the 'Lorenz Curve'?", "answer": "Graphical representation of income distribution"},
    {"question": "The Planning Commission of India was replaced by?", "answer": "NITI Aayog"},
    {"question": "What is 'Fiduciary Issue' of currency?", "answer": "Notes issued not backed by gold but by the government's promise"},
    {"question": "The 'Kuznets Curve' for environmental quality shows?", "answer": "Pollution first increases then decreases with income growth"},
    {"question": "Which country has the highest Human Development Index (HDI)?", "answer": "Norway"},
    {"question": "What does 'CPI' measure?", "answer": "Change in prices of a basket of consumer goods"},
    {"question": "The concept of 'Creative Destruction' was given by?", "answer": "Joseph Schumpeter"},
    {"question": "The Union Budget in India is presented in which month?", "answer": "February 1st"},
    {"question": "What is 'Venture Capital'?", "answer": "Financing provided to early-stage high-potential companies"},
    {"question": "The term 'Liquidity Trap' is associated with which economist?", "answer": "John Maynard Keynes"},
    {"question": "SIDBI stands for?", "answer": "Small Industries Development Bank of India"},
    {"question": "What is 'Quantitative Easing'?", "answer": "Central bank buying financial assets to inject money into economy"},
    {"question": "The Gold Standard was officially abandoned globally in which era?", "answer": "1971 (Bretton Woods collapse)"},
    {"question": "Which sector is called the 'Backbone of the Indian Economy'?", "answer": "Agriculture"},
    {"question": "The PMSBY scheme provides?", "answer": "Accidental death and disability insurance"},
    {"question": "What is 'Capital Adequacy Ratio' (CAR)?", "answer": "Minimum capital a bank must hold as percentage of its risk-weighted assets"},
    {"question": "Which index measures wholesale price inflation in India?", "answer": "Wholesale Price Index (WPI)"},
    {"question": "The term 'Monopsony' refers to?", "answer": "A market with a single buyer"},
    {"question": "The 'Big Push Theory' of development was proposed by?", "answer": "Paul Rosenstein-Rodan"},
    {"question": "What is 'Transfer Pricing'?", "answer": "Price set for transactions between related parties of a business"},
    {"question": "The Foreign Exchange Management Act (FEMA) replaced?", "answer": "Foreign Exchange Regulation Act (FERA)"},
    {"question": "Which country has the highest per capita income?", "answer": "Luxembourg"},
    {"question": "What is 'Marginal Propensity to Consume' (MPC)?", "answer": "Fraction of additional income spent on consumption"},
    {"question": "The 'Vicious Cycle of Poverty' concept was given by?", "answer": "Ragnar Nurkse"},
    {"question": "What is 'Equity' in financial terms?", "answer": "The value of shares in a company"},
    {"question": "The Pradhan Mantri Awas Yojana is aimed at?", "answer": "Providing housing for all"},
    {"question": "What does 'LIBOR' stand for?", "answer": "London Interbank Offered Rate"},
    {"question": "Which is the oldest multilateral development bank?", "answer": "World Bank"},
    {"question": "The concept of 'Dumping' in trade means?", "answer": "Selling goods in foreign markets below their cost of production"},
    {"question": "The Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) provides how much income support per year?", "answer": "Rs 6,000 per year"},
    {"question": "What is the 'Elasticity of Demand'?", "answer": "Degree to which demand changes in response to price change"},
    {"question": "The Global Competitiveness Report is published by?", "answer": "World Economic Forum (WEF)"},
    {"question": "What is 'Money Laundering'?", "answer": "Making illegally obtained money appear legitimate"},
    {"question": "Which scheme covers free LPG connections for BPL families?", "answer": "Pradhan Mantri Ujjwala Yojana"},
    {"question": "What is the 'Poverty Gap Index'?", "answer": "Average shortfall of income from the poverty line"},
    {"question": "The Asian Development Bank (ADB) is headquartered in?", "answer": "Manila, Philippines"},
    {"question": "What is 'Crowding Out Effect'?", "answer": "Government borrowing reduces availability of funds for private investment"},
    {"question": "The RBI was set up based on recommendations of?", "answer": "Hilton Young Commission"},
    {"question": "What is 'Moral Hazard' in economics?", "answer": "Risk that a party insulated from risk behaves differently than if fully exposed"},
    {"question": "The concept of 'Social Capital' was popularized by?", "answer": "Robert Putnam"},
    {"question": "Prime Lending Rate is set by?", "answer": "Commercial banks"},
    {"question": "What is 'Hyperinflation'?", "answer": "Extremely rapid or out-of-control inflation"},
    {"question": "The National Pension System (NPS) in India is regulated by?", "answer": "PFRDA (Pension Fund Regulatory and Development Authority)"},
    {"question": "Which is the largest economy in Asia?", "answer": "China"},
    {"question": "The repo rate is the rate at which?", "answer": "RBI lends money to commercial banks"},
    {"question": "The term 'Invisible Exports' refers to?", "answer": "Services sold abroad, like tourism and software"},
    {"question": "What is 'Stagflation'?", "answer": "Simultaneous occurrence of high unemployment and high inflation"},
    {"question": "PPF stands for?", "answer": "Public Provident Fund"},
    {"question": "The Pradhan Mantri Rozgar Protsahan Yojana (PMRPY) is aimed at?", "answer": "Generating employment by incentivizing employers"},
    {"question": "The 'Opportunity Cost' is defined as?", "answer": "The value of the next best alternative foregone"},
    {"question": "Which act prevents insider trading in India?", "answer": "SEBI Insider Trading Regulations"},
    {"question": "What is 'Monetary Transmission Mechanism'?", "answer": "The process through which monetary policy impacts the broader economy"},
    {"question": "What are G20 countries also known as?", "answer": "Major world economies"},
    {"question": "The 'Engel's Law' states that as income rises?", "answer": "The percentage spent on food declines"},
    {"question": "What is 'Microfinance'?", "answer": "Financial services for low-income individuals and businesses"},
    {"question": "The Annual GDP growth rate is also called?", "answer": "Economic growth rate"},
    {"question": "What is a 'Current Account Deficit'?", "answer": "When imports of goods, services, and transfers exceed exports"},
    {"question": "The National Investment and Infrastructure Fund (NIIF) was set up in?", "answer": "2015"},
    {"question": "The 'Marginal Utility' theory was proposed by?", "answer": "William Stanley Jevons"},
    {"question": "PAN card stands for?", "answer": "Permanent Account Number"},
    {"question": "What is the 'Laffer Curve'?", "answer": "Relationship between tax rates and tax revenue collected"},
    {"question": "What are 'Blue-chip stocks'?", "answer": "Shares of well-established, financially stable companies"},
]

# Top up geography
existing_geo = data['geography']
needed = 500 - len(existing_geo)
if needed > 0:
    existing_q_strs = {q['question'] for q in existing_geo}
    added = 0
    for q in extra_geography:
        if added >= needed:
            break
        if q['question'] not in existing_q_strs:
            existing_geo.append({"id": len(existing_geo) + 1, "question": q['question'], "answer": q['answer']})
            existing_q_strs.add(q['question'])
            added += 1
    data['geography'] = existing_geo
    print(f"Geography: {len(existing_geo)} questions")

# Top up economy
existing_eco = data['economy']
needed_eco = 500 - len(existing_eco)
if needed_eco > 0:
    existing_q_strs_eco = {q['question'] for q in existing_eco}
    added_eco = 0
    for q in extra_economy:
        if added_eco >= needed_eco:
            break
        if q['question'] not in existing_q_strs_eco:
            existing_eco.append({"id": len(existing_eco) + 1, "question": q['question'], "answer": q['answer']})
            existing_q_strs_eco.add(q['question'])
            added_eco += 1
    data['economy'] = existing_eco
    print(f"Economy: {len(existing_eco)} questions")

# Verify all
for topic, qs in data.items():
    print(f"{topic}: {len(qs)} questions")

# Write
js = f"const questions_upsc = {json.dumps(data, indent=2)};\n"
open('questions_upsc.js', 'w', encoding='utf-8').write(js)
print("Done! Written to questions_upsc.js")
